export const patients = [
  {
    id: '1',
    creation_date: '07/03/2022 12:06',
    case_key: 'VETCT-1',
    patient: 'Michele Roberts',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'Roy Brown',
    reporting_specialist: 'Clark Kent',
    species: 'Canine,German Shepherd Dog',
    body_areas: 'Head,Thorax',
    turnaround: 'Standard',
    reported_date: '08/03/2022 12:06',
    image_url: 'https://images.dog.ceo/breeds/dachshund/foxhound-53951_640.jpg',
  },
  {
    id: '2',
    creation_date: '08/03/2022 22:07',
    case_key: 'VETCT-2',
    patient: 'Kristen Cruz',
    status: 'Add History',
    specialty: 'XRAY',
    owner: 'Alexandra Moon',
    reporting_specialist: 'Joe Blogg',
    species: 'Feline,Shorthair',
    body_areas: 'Thorax',
    turnaround: 'Urgent',
    reported_date: '09/03/2022 22:07',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '3',
    creation_date: '10/03/2022 08:08',
    case_key: 'VETCT-3',
    patient: 'Brandon Singleton',
    status: 'Reported',
    specialty: 'CT',
    owner: 'Angelica Newton',
    reporting_specialist: 'Frank Jones',
    species: 'Canine,Cocker Spaniel',
    body_areas: 'Carpus-Left,Carpus-Right',
    turnaround: 'Priority',
    reported_date: '11/03/2022 08:08',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund-1018409_640.jpg',
  },
  {
    id: '4',
    creation_date: '11/03/2022 18:09',
    case_key: 'VETCT-4',
    patient: 'Keith Kelly',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'Stephen Whitehead',
    reporting_specialist: 'Jacob Harrison',
    species: 'Canine,Poodle',
    body_areas: 'Elbow-Right',
    turnaround: 'Standard',
    reported_date: '12/03/2022 18:09',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '5',
    creation_date: '13/03/2022 04:10',
    case_key: 'VETCT-5',
    patient: 'Christina Butler',
    status: 'Add History',
    specialty: 'XRAY',
    owner: 'Richard Johnson',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Schnauzer',
    body_areas: 'Neck,Shoulder',
    turnaround: 'Priority',
    reported_date: '14/03/2022 04:10',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '6',
    creation_date: '14/03/2022 14:11',
    case_key: 'VETCT-6',
    patient: 'Rhonda Rivera',
    status: 'Add History',
    specialty: 'CT',
    owner: 'Tiffany Mcbride',
    reporting_specialist: 'Claire Fielding',
    species: 'Canine,Pointer',
    body_areas: 'Head',
    turnaround: 'Standard',
    reported_date: '15/03/2022 14:11',
    image_url: 'https://images.dog.ceo/breeds/dachshund/foxhound-53951_640.jpg',
  },
  {
    id: '7',
    creation_date: '16/03/2022 00:12',
    case_key: 'VETCT-7',
    patient: 'Dana Jones',
    status: 'On Hold',
    specialty: 'MRI',
    owner: 'Francisco Hernandez',
    reporting_specialist: 'Pauline Booth',
    species: 'Canine,German Shepherd Dog',
    body_areas: 'Thorax,Head,Neck',
    turnaround: 'Standard',
    reported_date: '17/03/2022 00:12',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '8',
    creation_date: '17/03/2022 10:13',
    case_key: 'VETCT-8',
    patient: 'Brittany Davis',
    status: 'Reported',
    specialty: 'XRAY',
    owner: 'Nancy Santiago',
    reporting_specialist: 'Kate James',
    species: 'Feline,Shorthair',
    body_areas: 'Carpus-Left',
    turnaround: 'Standard',
    reported_date: '18/03/2022 10:13',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund-1018409_640.jpg',
  },
  {
    id: '9',
    creation_date: '18/03/2022 20:14',
    case_key: 'VETCT-9',
    patient: 'Wayne Coffey',
    status: 'Reported',
    specialty: 'CT',
    owner: 'Christine Smith',
    reporting_specialist: 'Clark Kent',
    species: 'Canine,Cocker Spaniel',
    body_areas: 'Elbow-Right',
    turnaround: 'Urgent',
    reported_date: '19/03/2022 20:14',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '10',
    creation_date: '20/03/2022 06:15',
    case_key: 'VETCT-10',
    patient: 'Richard Sutton',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'Wendy Hunt',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Poodle',
    body_areas: 'Neck',
    turnaround: 'Urgent',
    reported_date: '21/03/2022 06:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '11',
    creation_date: '22/03/2022 16:16',
    case_key: 'VETCT-11',
    patient: 'Joseph Adams',
    status: 'On Hold',
    specialty: 'XRAY',
    owner: 'Deanna Smith',
    reporting_specialist: 'Frank Jones',
    species: 'Canine,Schnauzer',
    body_areas: 'Abdomen',
    turnaround: 'Standard',
    reported_date: '23/03/2022 16:16',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund-1018409_640.jpg',
  },
  {
    id: '12',
    creation_date: '23/03/2022 02:17',
    case_key: 'VETCT-12',
    patient: 'Eugene Evans',
    status: 'Open',
    specialty: 'CT',
    owner: 'Theresa Castillo',
    reporting_specialist: 'Jacob Harrison',
    species: 'Canine,Pointer',
    body_areas: 'Pelvis',
    turnaround: 'Standard',
    reported_date: '24/03/2022 02:17',
    image_url: 'https://images.dog.ceo/breeds/dachshund/foxhound-53951_640.jpg',
  },
  {
    id: '13',
    creation_date: '24/03/2022 12:18',
    case_key: 'VETCT-13',
    patient: 'Dr. Raymond Salazar',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'Connor Elliott',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,German Shepherd Dog',
    body_areas: 'Abdomen,Pelvis,Spine',
    turnaround: 'Priority',
    reported_date: '25/03/2022 12:18',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '14',
    creation_date: '25/03/2022 22:19',
    case_key: 'VETCT-14',
    patient: 'Deborah Silva',
    status: 'Add History',
    specialty: 'XRAY',
    owner: 'Barbara Ramsey',
    reporting_specialist: 'Claire Fielding',
    species: 'Feline,Shorthair',
    body_areas: 'Elbow-Right',
    turnaround: 'Standard',
    reported_date: '26/03/2022 22:19',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '15',
    creation_date: '26/03/2022 12:22',
    case_key: 'VETCT-15',
    patient: 'Samantha Torres',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'Liam Turner',
    reporting_specialist: 'Clark Kent',
    species: 'Canine,Beagle',
    body_areas: 'Head',
    turnaround: 'Standard',
    reported_date: '27/03/2022 12:22',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund-1018409_640.jpg',
  },
  {
    id: '16',
    creation_date: '27/03/2022 16:18',
    case_key: 'VETCT-16',
    patient: 'Thomas King',
    status: 'On Hold',
    specialty: 'XRAY',
    owner: 'Olivia Diaz',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Bulldog',
    body_areas: 'Thorax',
    turnaround: 'Urgent',
    reported_date: '28/03/2022 16:18',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '17',
    creation_date: '28/03/2022 09:45',
    case_key: 'VETCT-17',
    patient: 'Emily Sanders',
    status: 'Reported',
    specialty: 'CT',
    owner: 'Sofia Lewis',
    reporting_specialist: 'Frank Jones',
    species: 'Canine,Labrador',
    body_areas: 'Abdomen',
    turnaround: 'Priority',
    reported_date: '29/03/2022 09:45',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund-1018409_640.jpg',
  },
  {
    id: '18',
    creation_date: '29/03/2022 12:30',
    case_key: 'VETCT-18',
    patient: 'Lucas White',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'James Harris',
    reporting_specialist: 'Jacob Harrison',
    species: 'Canine,Golden Retriever',
    body_areas: 'Pelvis',
    turnaround: 'Standard',
    reported_date: '30/03/2022 12:30',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '19',
    creation_date: '30/03/2022 10:20',
    case_key: 'VETCT-19',
    patient: 'Isabella Clark',
    status: 'Add History',
    specialty: 'XRAY',
    owner: 'Ava Walker',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Neck,Thorax',
    turnaround: 'Standard',
    reported_date: '31/03/2022 10:20',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '20',
    creation_date: '31/03/2022 15:55',
    case_key: 'VETCT-20',
    patient: 'Evelyn Allen',
    status: 'Reported',
    specialty: 'CT',
    owner: 'Charlotte Scott',
    reporting_specialist: 'Claire Fielding',
    species: 'Canine,Boxer',
    body_areas: 'Head,Neck',
    turnaround: 'Priority',
    reported_date: '01/04/2022 15:55',
    image_url: 'https://images.dog.ceo/breeds/dachshund/foxhound-53951_640.jpg',
  },
  {
    id: '21',
    creation_date: '01/04/2022 08:44',
    case_key: 'VETCT-21',
    patient: 'Daniel Young',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'Harper Hill',
    reporting_specialist: 'Pauline Booth',
    species: 'Canine,Rottweiler',
    body_areas: 'Pelvis,Spine',
    turnaround: 'Standard',
    reported_date: '02/04/2022 08:44',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '22',
    creation_date: '02/04/2022 13:32',
    case_key: 'VETCT-22',
    patient: 'Matthew Wright',
    status: 'Open',
    specialty: 'XRAY',
    owner: 'Liam Martinez',
    reporting_specialist: 'Frank Jones',
    species: 'Canine,Chihuahua',
    body_areas: 'Thorax,Abdomen',
    turnaround: 'Urgent',
    reported_date: '03/04/2022 13:32',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund-1018409_640.jpg',
  },
  {
    id: '23',
    creation_date: '03/04/2022 11:11',
    case_key: 'VETCT-23',
    patient: 'David Green',
    status: 'Reported',
    specialty: 'CT',
    owner: 'James Anderson',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Dachshund',
    body_areas: 'Pelvis,Spine',
    turnaround: 'Standard',
    reported_date: '04/04/2022 11:11',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '24',
    creation_date: '04/04/2022 14:45',
    case_key: 'VETCT-24',
    patient: 'Olivia Robinson',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'Elizabeth Lee',
    reporting_specialist: 'Jacob Harrison',
    species: 'Canine,Great Dane',
    body_areas: 'Head,Neck',
    turnaround: 'Priority',
    reported_date: '05/04/2022 14:45',
    image_url: 'https://images.dog.ceo/breeds/dachshund/foxhound-53951_640.jpg',
  },
  {
    id: '25',
    creation_date: '05/04/2022 17:33',
    case_key: 'VETCT-25',
    patient: 'Sophia Brown',
    status: 'Add History',
    specialty: 'XRAY',
    owner: 'Michael Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Bulldog',
    body_areas: 'Neck,Thorax',
    turnaround: 'Standard',
    reported_date: '06/04/2022 17:33',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '26',
    creation_date: '06/04/2022 19:20',
    case_key: 'VETCT-26',
    patient: 'Lily Johnson',
    status: 'Reported',
    specialty: 'CT',
    owner: 'James Brown',
    reporting_specialist: 'Clark Kent',
    species: 'Canine,Labrador Retriever',
    body_areas: 'Thorax,Head',
    turnaround: 'Priority',
    reported_date: '07/04/2022 19:20',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '27',
    creation_date: '07/04/2022 09:15',
    case_key: 'VETCT-27',
    patient: 'Michael Smith',
    status: 'On Hold',
    specialty: 'MRI',
    owner: 'Mary Wilson',
    reporting_specialist: 'Joe Blogg',
    species: 'Feline,Persian',
    body_areas: 'Abdomen',
    turnaround: 'Standard',
    reported_date: '08/04/2022 09:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund-1018409_640.jpg',
  },
  {
    id: '28',
    creation_date: '08/04/2022 13:45',
    case_key: 'VETCT-28',
    patient: 'Anna Taylor',
    status: 'Reported',
    specialty: 'XRAY',
    owner: 'Linda Harris',
    reporting_specialist: 'Frank Jones',
    species: 'Canine,Boxer',
    body_areas: 'Neck,Thorax',
    turnaround: 'Urgent',
    reported_date: '09/04/2022 13:45',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '29',
    creation_date: '09/04/2022 14:30',
    case_key: 'VETCT-29',
    patient: 'Sophia Moore',
    status: 'Open',
    specialty: 'CT',
    owner: 'Robert Martinez',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Abdomen,Spine',
    turnaround: 'Priority',
    reported_date: '10/04/2022 14:30',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '30',
    creation_date: '10/04/2022 12:22',
    case_key: 'VETCT-30',
    patient: 'Olivia Jackson',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'Patricia Anderson',
    reporting_specialist: 'Jacob Harrison',
    species: 'Canine,Dachshund',
    body_areas: 'Pelvis,Thorax',
    turnaround: 'Standard',
    reported_date: '11/04/2022 12:22',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund-1018409_640.jpg',
  },
  {
    id: '31',
    creation_date: '11/04/2022 09:30',
    case_key: 'VETCT-31',
    patient: 'Mason Thomas',
    status: 'Add History',
    specialty: 'XRAY',
    owner: 'Lisa Robinson',
    reporting_specialist: 'Claire Fielding',
    species: 'Canine,Bulldog',
    body_areas: 'Head,Neck',
    turnaround: 'Standard',
    reported_date: '12/04/2022 09:30',
    image_url: 'https://images.dog.ceo/breeds/dachshund/foxhound-53951_640.jpg',
  },
  {
    id: '32',
    creation_date: '12/04/2022 17:18',
    case_key: 'VETCT-32',
    patient: 'James Martinez',
    status: 'On Hold',
    specialty: 'CT',
    owner: 'Charles Clark',
    reporting_specialist: 'Pauline Booth',
    species: 'Canine,German Shepherd Dog',
    body_areas: 'Thorax,Head',
    turnaround: 'Urgent',
    reported_date: '13/04/2022 17:18',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '33',
    creation_date: '13/04/2022 08:45',
    case_key: 'VETCT-33',
    patient: 'Emily White',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'Barbara Wright',
    reporting_specialist: 'Frank Jones',
    species: 'Canine,Labrador',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '14/04/2022 08:45',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '34',
    creation_date: '14/04/2022 11:32',
    case_key: 'VETCT-34',
    patient: 'Joshua Harris',
    status: 'Add History',
    specialty: 'XRAY',
    owner: 'Christopher Lewis',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Beagle',
    body_areas: 'Neck,Thorax',
    turnaround: 'Standard',
    reported_date: '15/04/2022 11:32',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '35',
    creation_date: '15/04/2022 15:20',
    case_key: 'VETCT-35',
    patient: 'Madison Hall',
    status: 'Reported',
    specialty: 'CT',
    owner: 'Sarah King',
    reporting_specialist: 'Jacob Harrison',
    species: 'Canine,Golden Retriever',
    body_areas: 'Head,Neck',
    turnaround: 'Standard',
    reported_date: '16/04/2022 15:20',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '36',
    creation_date: '16/04/2022 19:18',
    case_key: 'VETCT-36',
    patient: 'David Walker',
    status: 'On Hold',
    specialty: 'MRI',
    owner: 'Karen Rodriguez',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '17/04/2022 19:18',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund-1018409_640.jpg',
  },
  {
    id: '37',
    creation_date: '17/04/2022 12:45',
    case_key: 'VETCT-37',
    patient: 'Ethan Hernandez',
    status: 'Reported',
    specialty: 'XRAY',
    owner: 'Patricia Martinez',
    reporting_specialist: 'Clark Kent',
    species: 'Canine,Bulldog',
    body_areas: 'Abdomen',
    turnaround: 'Urgent',
    reported_date: '18/04/2022 12:45',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '38',
    creation_date: '18/04/2022 08:30',
    case_key: 'VETCT-38',
    patient: 'Abigail Gonzalez',
    status: 'Add History',
    specialty: 'CT',
    owner: 'Larry Davis',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,German Shepherd Dog',
    body_areas: 'Head,Neck',
    turnaround: 'Priority',
    reported_date: '19/04/2022 08:30',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '39',
    creation_date: '19/04/2022 15:15',
    case_key: 'VETCT-39',
    patient: 'Isabella Hall',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'Linda Lewis',
    reporting_specialist: 'Jacob Harrison',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Standard',
    reported_date: '20/04/2022 15:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '40',
    creation_date: '20/04/2022 12:32',
    case_key: 'VETCT-40',
    patient: 'Mia King',
    status: 'Add History',
    specialty: 'XRAY',
    owner: 'James Walker',
    reporting_specialist: 'Frank Jones',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Spine',
    turnaround: 'Standard',
    reported_date: '21/04/2022 12:32',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '41',
    creation_date: '21/04/2022 09:15',
    case_key: 'VETCT-41',
    patient: 'Oliver Johnson',
    status: 'On Hold',
    specialty: 'CT',
    owner: 'Angela Harris',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Bulldog',
    body_areas: 'Thorax,Head',
    turnaround: 'Urgent',
    reported_date: '22/04/2022 09:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund-1018409_640.jpg',
  },
  {
    id: '42',
    creation_date: '22/04/2022 14:45',
    case_key: 'VETCT-42',
    patient: 'Daniel Martinez',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'Christopher Lee',
    reporting_specialist: 'Clark Kent',
    species: 'Canine,Labrador Retriever',
    body_areas: 'Neck,Thorax',
    turnaround: 'Priority',
    reported_date: '23/04/2022 14:45',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '43',
    creation_date: '23/04/2022 11:32',
    case_key: 'VETCT-43',
    patient: 'Logan Rodriguez',
    status: 'Add History',
    specialty: 'XRAY',
    owner: 'Sandra Allen',
    reporting_specialist: 'Frank Jones',
    species: 'Canine,German Shepherd Dog',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Standard',
    reported_date: '24/04/2022 11:32',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '44',
    creation_date: '24/04/2022 15:20',
    case_key: 'VETCT-44',
    patient: 'Jackson Lewis',
    status: 'Reported',
    specialty: 'CT',
    owner: 'Rebecca Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Head,Neck',
    turnaround: 'Priority',
    reported_date: '25/04/2022 15:20',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '45',
    creation_date: '25/04/2022 18:18',
    case_key: 'VETCT-45',
    patient: 'Sophia Clark',
    status: 'On Hold',
    specialty: 'MRI',
    owner: 'Matthew Scott',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Thorax,Spine',
    turnaround: 'Urgent',
    reported_date: '26/04/2022 18:18',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund-1018409_640.jpg',
  },
  {
    id: '46',
    creation_date: '26/04/2022 12:45',
    case_key: 'VETCT-46',
    patient: 'Emily King',
    status: 'Reported',
    specialty: 'XRAY',
    owner: 'Brandon Adams',
    reporting_specialist: 'Clark Kent',
    species: 'Canine,Bulldog',
    body_areas: 'Abdomen',
    turnaround: 'Priority',
    reported_date: '27/04/2022 12:45',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '47',
    creation_date: '27/04/2022 08:30',
    case_key: 'VETCT-47',
    patient: 'Jacob Lopez',
    status: 'Add History',
    specialty: 'CT',
    owner: 'Kenneth Lee',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,German Shepherd Dog',
    body_areas: 'Head,Neck',
    turnaround: 'Priority',
    reported_date: '28/04/2022 08:30',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '48',
    creation_date: '28/04/2022 10:15',
    case_key: 'VETCT-48',
    patient: 'Mason White',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'Anna King',
    reporting_specialist: 'Jacob Harrison',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Standard',
    reported_date: '29/04/2022 10:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '49',
    creation_date: '29/04/2022 14:30',
    case_key: 'VETCT-49',
    patient: 'Lucas Martin',
    status: 'Add History',
    specialty: 'XRAY',
    owner: 'James Walker',
    reporting_specialist: 'Frank Jones',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Spine',
    turnaround: 'Standard',
    reported_date: '30/04/2022 14:30',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '50',
    creation_date: '30/04/2022 15:15',
    case_key: 'VETCT-50',
    patient: 'Ella Young',
    status: 'Reported',
    specialty: 'CT',
    owner: 'William Harris',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Bulldog',
    body_areas: 'Thorax,Head',
    turnaround: 'Urgent',
    reported_date: '01/05/2022 15:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund-1018409_640.jpg',
  },
  {
    id: '51',
    creation_date: '01/05/2022 12:32',
    case_key: 'VETCT-51',
    patient: 'Samantha Gonzalez',
    status: 'Add History',
    specialty: 'MRI',
    owner: 'Deborah Harris',
    reporting_specialist: 'Clark Kent',
    species: 'Canine,Labrador Retriever',
    body_areas: 'Neck,Thorax',
    turnaround: 'Priority',
    reported_date: '02/05/2022 12:32',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '52',
    creation_date: '02/05/2022 09:15',
    case_key: 'VETCT-52',
    patient: 'Matthew Clark',
    status: 'Reported',
    specialty: 'XRAY',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Frank Jones',
    species: 'Canine,German Shepherd Dog',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Standard',
    reported_date: '03/05/2022 09:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '53',
    creation_date: '03/05/2022 11:32',
    case_key: 'VETCT-53',
    patient: 'Ethan Davis',
    status: 'Add History',
    specialty: 'CT',
    owner: 'Linda Walker',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Head,Neck',
    turnaround: 'Priority',
    reported_date: '04/05/2022 11:32',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '54',
    creation_date: '04/05/2022 14:45',
    case_key: 'VETCT-54',
    patient: 'Michael Harris',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'Sandra Lewis',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Thorax,Spine',
    turnaround: 'Urgent',
    reported_date: '05/05/2022 14:45',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund-1018409_640.jpg',
  },
  {
    id: '55',
    creation_date: '05/05/2022 12:15',
    case_key: 'VETCT-55',
    patient: 'Emma Brown',
    status: 'Add History',
    specialty: 'XRAY',
    owner: 'Patricia King',
    reporting_specialist: 'Clark Kent',
    species: 'Canine,Bulldog',
    body_areas: 'Abdomen',
    turnaround: 'Standard',
    reported_date: '06/05/2022 12:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '56',
    creation_date: '06/05/2022 14:30',
    case_key: 'VETCT-56',
    patient: 'Liam Garcia',
    status: 'Reported',
    specialty: 'CT',
    owner: 'James Rodriguez',
    reporting_specialist: 'Frank Jones',
    species: 'Canine,German Shepherd Dog',
    body_areas: 'Neck,Thorax',
    turnaround: 'Priority',
    reported_date: '07/05/2022 14:30',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '57',
    creation_date: '07/05/2022 10:18',
    case_key: 'VETCT-57',
    patient: 'Evelyn Martinez',
    status: 'Add History',
    specialty: 'MRI',
    owner: 'Christopher Lee',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Abdomen,Spine',
    turnaround: 'Priority',
    reported_date: '08/05/2022 10:18',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '58',
    creation_date: '08/05/2022 15:20',
    case_key: 'VETCT-58',
    patient: 'Benjamin Clark',
    status: 'On Hold',
    specialty: 'XRAY',
    owner: 'Deborah Harris',
    reporting_specialist: 'Clark Kent',
    species: 'Canine,Golden Retriever',
    body_areas: 'Head,Neck',
    turnaround: 'Standard',
    reported_date: '09/05/2022 15:20',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '59',
    creation_date: '09/05/2022 17:18',
    case_key: 'VETCT-59',
    patient: 'Chloe Hill',
    status: 'Reported',
    specialty: 'CT',
    owner: 'Robert Anderson',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '10/05/2022 17:18',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund-1018409_640.jpg',
  },
  {
    id: '60',
    creation_date: '10/05/2022 14:30',
    case_key: 'VETCT-60',
    patient: 'Samantha Walker',
    status: 'Add History',
    specialty: 'MRI',
    owner: 'James King',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,German Shepherd Dog',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '11/05/2022 14:30',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '61',
    creation_date: '11/05/2022 10:15',
    case_key: 'VETCT-61',
    patient: 'Ethan Harris',
    status: 'Reported',
    specialty: 'XRAY',
    owner: 'Brandon Johnson',
    reporting_specialist: 'Frank Jones',
    species: 'Canine,Poodle',
    body_areas: 'Head,Neck',
    turnaround: 'Urgent',
    reported_date: '12/05/2022 10:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '62',
    creation_date: '12/05/2022 11:32',
    case_key: 'VETCT-62',
    patient: 'Michael Johnson',
    status: 'Add History',
    specialty: 'CT',
    owner: 'Patricia King',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Labrador Retriever',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '13/05/2022 11:32',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '63',
    creation_date: '13/05/2022 15:20',
    case_key: 'VETCT-63',
    patient: 'Chloe White',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'Matthew Anderson',
    reporting_specialist: 'Frank Jones',
    species: 'Canine,Poodle',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '14/05/2022 15:20',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '64',
    creation_date: '14/05/2022 12:18',
    case_key: 'VETCT-64',
    patient: 'Mason Harris',
    status: 'Add History',
    specialty: 'XRAY',
    owner: 'Anna Lewis',
    reporting_specialist: 'Clark Kent',
    species: 'Canine,Golden Retriever',
    body_areas: 'Head,Neck',
    turnaround: 'Standard',
    reported_date: '15/05/2022 12:18',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '65',
    creation_date: '15/05/2022 09:15',
    case_key: 'VETCT-65',
    patient: 'Jacob Clark',
    status: 'Reported',
    specialty: 'CT',
    owner: 'Christopher King',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '16/05/2022 09:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '66',
    creation_date: '16/05/2022 11:32',
    case_key: 'VETCT-66',
    patient: 'Logan Walker',
    status: 'Add History',
    specialty: 'MRI',
    owner: 'Deborah Johnson',
    reporting_specialist: 'Frank Jones',
    species: 'Canine,German Shepherd Dog',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '17/05/2022 11:32',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '67',
    creation_date: '17/05/2022 14:45',
    case_key: 'VETCT-67',
    patient: 'Ella Lee',
    status: 'Reported',
    specialty: 'XRAY',
    owner: 'James Harris',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Head,Neck',
    turnaround: 'Urgent',
    reported_date: '18/05/2022 14:45',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '68',
    creation_date: '18/05/2022 12:15',
    case_key: 'VETCT-68',
    patient: 'Samantha White',
    status: 'Add History',
    specialty: 'CT',
    owner: 'Patricia King',
    reporting_specialist: 'Clark Kent',
    species: 'Canine,Bulldog',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '19/05/2022 12:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '69',
    creation_date: '19/05/2022 14:30',
    case_key: 'VETCT-69',
    patient: 'Ethan Garcia',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Frank Jones',
    species: 'Canine,Labrador Retriever',
    body_areas: 'Head,Neck',
    turnaround: 'Urgent',
    reported_date: '20/05/2022 14:30',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '70',
    creation_date: '20/05/2022 10:18',
    case_key: 'VETCT-70',
    patient: 'Benjamin Johnson',
    status: 'Add History',
    specialty: 'XRAY',
    owner: 'Christopher King',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '21/05/2022 10:18',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '71',
    creation_date: '21/05/2022 15:20',
    case_key: 'VETCT-71',
    patient: 'Chloe Harris',
    status: 'On Hold',
    specialty: 'CT',
    owner: 'Anna Lewis',
    reporting_specialist: 'Clark Kent',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '22/05/2022 15:20',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '72',
    creation_date: '22/05/2022 09:15',
    case_key: 'VETCT-72',
    patient: 'Jacob Clark',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'Deborah King',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Poodle',
    body_areas: 'Head,Neck',
    turnaround: 'Urgent',
    reported_date: '23/05/2022 09:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '73',
    creation_date: '23/05/2022 11:32',
    case_key: 'VETCT-73',
    patient: 'Mason Johnson',
    status: 'Add History',
    specialty: 'XRAY',
    owner: 'James Harris',
    reporting_specialist: 'Frank Jones',
    species: 'Canine,Golden Retriever',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '24/05/2022 11:32',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '74',
    creation_date: '24/05/2022 14:45',
    case_key: 'VETCT-74',
    patient: 'Ella White',
    status: 'Reported',
    specialty: 'CT',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Head,Neck',
    turnaround: 'Priority',
    reported_date: '25/05/2022 14:45',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '75',
    creation_date: '25/05/2022 12:18',
    case_key: 'VETCT-75',
    patient: 'Chloe Harris',
    status: 'Add History',
    specialty: 'MRI',
    owner: 'Patricia King',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '26/05/2022 12:18',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '76',
    creation_date: '26/05/2022 09:15',
    case_key: 'VETCT-76',
    patient: 'Mason Clark',
    status: 'Reported',
    specialty: 'XRAY',
    owner: 'James Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '27/05/2022 09:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '77',
    creation_date: '27/05/2022 11:32',
    case_key: 'VETCT-77',
    patient: 'Chloe White',
    status: 'Add History',
    specialty: 'CT',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Frank Jones',
    species: 'Canine,Golden Retriever',
    body_areas: 'Head,Neck',
    turnaround: 'Priority',
    reported_date: '28/05/2022 11:32',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '78',
    creation_date: '28/05/2022 14:45',
    case_key: 'VETCT-78',
    patient: 'Ella Johnson',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'Patricia King',
    reporting_specialist: 'Clark Kent',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '29/05/2022 14:45',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '79',
    creation_date: '29/05/2022 12:18',
    case_key: 'VETCT-79',
    patient: 'Mason Harris',
    status: 'Add History',
    specialty: 'XRAY',
    owner: 'James White',
    reporting_specialist: 'Frank Jones',
    species: 'Canine,Golden Retriever',
    body_areas: 'Head,Neck',
    turnaround: 'Priority',
    reported_date: '30/05/2022 12:18',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '80',
    creation_date: '30/05/2022 09:15',
    case_key: 'VETCT-80',
    patient: 'Jacob Clark',
    status: 'Reported',
    specialty: 'CT',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '31/05/2022 09:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '81',
    creation_date: '31/05/2022 11:32',
    case_key: 'VETCT-81',
    patient: 'Mason Harris',
    status: 'Add History',
    specialty: 'MRI',
    owner: 'Patricia King',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '01/06/2022 11:32',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '82',
    creation_date: '01/06/2022 14:45',
    case_key: 'VETCT-82',
    patient: 'Ella Johnson',
    status: 'Reported',
    specialty: 'XRAY',
    owner: 'James Harris',
    reporting_specialist: 'Frank Jones',
    species: 'Canine,Poodle',
    body_areas: 'Head,Neck',
    turnaround: 'Priority',
    reported_date: '02/06/2022 14:45',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '83',
    creation_date: '02/06/2022 12:18',
    case_key: 'VETCT-83',
    patient: 'Mason Clark',
    status: 'Add History',
    specialty: 'CT',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Golden Retriever',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '03/06/2022 12:18',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '84',
    creation_date: '03/06/2022 09:15',
    case_key: 'VETCT-84',
    patient: 'Jacob White',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'James Harris',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Poodle',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '04/06/2022 09:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '85',
    creation_date: '04/06/2022 11:32',
    case_key: 'VETCT-85',
    patient: 'Mason Harris',
    status: 'Add History',
    specialty: 'XRAY',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Golden Retriever',
    body_areas: 'Head,Neck',
    turnaround: 'Priority',
    reported_date: '05/06/2022 11:32',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '86',
    creation_date: '05/06/2022 14:45',
    case_key: 'VETCT-86',
    patient: 'Ella Johnson',
    status: 'Reported',
    specialty: 'CT',
    owner: 'James Harris',
    reporting_specialist: 'Frank Jones',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '06/06/2022 14:45',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '87',
    creation_date: '06/06/2022 12:18',
    case_key: 'VETCT-87',
    patient: 'Mason Clark',
    status: 'Add History',
    specialty: 'MRI',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '07/06/2022 12:18',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '88',
    creation_date: '07/06/2022 09:15',
    case_key: 'VETCT-88',
    patient: 'Jacob White',
    status: 'Reported',
    specialty: 'XRAY',
    owner: 'James Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '08/06/2022 09:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '89',
    creation_date: '08/06/2022 11:32',
    case_key: 'VETCT-89',
    patient: 'Mason Harris',
    status: 'Add History',
    specialty: 'CT',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Head,Neck',
    turnaround: 'Priority',
    reported_date: '09/06/2022 11:32',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '90',
    creation_date: '09/06/2022 14:45',
    case_key: 'VETCT-90',
    patient: 'Ella Johnson',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'James Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '10/06/2022 14:45',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '91',
    creation_date: '10/06/2022 12:18',
    case_key: 'VETCT-91',
    patient: 'Mason Clark',
    status: 'Add History',
    specialty: 'XRAY',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '11/06/2022 12:18',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '92',
    creation_date: '11/06/2022 09:15',
    case_key: 'VETCT-92',
    patient: 'Jacob White',
    status: 'Reported',
    specialty: 'CT',
    owner: 'James Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '12/06/2022 09:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '93',
    creation_date: '12/06/2022 11:32',
    case_key: 'VETCT-93',
    patient: 'Mason Harris',
    status: 'Add History',
    specialty: 'MRI',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '13/06/2022 11:32',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '94',
    creation_date: '13/06/2022 14:45',
    case_key: 'VETCT-94',
    patient: 'Ella Johnson',
    status: 'Reported',
    specialty: 'XRAY',
    owner: 'James Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '14/06/2022 14:45',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '95',
    creation_date: '14/06/2022 12:18',
    case_key: 'VETCT-95',
    patient: 'Mason Clark',
    status: 'Add History',
    specialty: 'CT',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '15/06/2022 12:18',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '96',
    creation_date: '15/06/2022 09:15',
    case_key: 'VETCT-96',
    patient: 'Jacob White',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'James Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '16/06/2022 09:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '97',
    creation_date: '16/06/2022 11:32',
    case_key: 'VETCT-97',
    patient: 'Mason Harris',
    status: 'Add History',
    specialty: 'XRAY',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '17/06/2022 11:32',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '98',
    creation_date: '17/06/2022 14:45',
    case_key: 'VETCT-98',
    patient: 'Ella Johnson',
    status: 'Reported',
    specialty: 'CT',
    owner: 'James Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '18/06/2022 14:45',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '99',
    creation_date: '18/06/2022 12:18',
    case_key: 'VETCT-99',
    patient: 'Mason Clark',
    status: 'Add History',
    specialty: 'MRI',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '19/06/2022 12:18',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '100',
    creation_date: '19/06/2022 09:15',
    case_key: 'VETCT-100',
    patient: 'Jacob White',
    status: 'Reported',
    specialty: 'XRAY',
    owner: 'James Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '20/06/2022 09:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '101',
    creation_date: '20/06/2022 11:32',
    case_key: 'VETCT-101',
    patient: 'Mason Harris',
    status: 'Add History',
    specialty: 'CT',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '21/06/2022 11:32',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '102',
    creation_date: '21/06/2022 14:45',
    case_key: 'VETCT-102',
    patient: 'Ella Johnson',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'James Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '22/06/2022 14:45',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '103',
    creation_date: '22/06/2022 12:18',
    case_key: 'VETCT-103',
    patient: 'Mason Clark',
    status: 'Add History',
    specialty: 'XRAY',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '23/06/2022 12:18',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '104',
    creation_date: '23/06/2022 09:15',
    case_key: 'VETCT-104',
    patient: 'Jacob White',
    status: 'Reported',
    specialty: 'CT',
    owner: 'James Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '24/06/2022 09:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '105',
    creation_date: '24/06/2022 11:32',
    case_key: 'VETCT-105',
    patient: 'Mason Harris',
    status: 'Add History',
    specialty: 'MRI',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '25/06/2022 11:32',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '106',
    creation_date: '25/06/2022 14:45',
    case_key: 'VETCT-106',
    patient: 'Ella Johnson',
    status: 'Reported',
    specialty: 'XRAY',
    owner: 'James Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '26/06/2022 14:45',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '107',
    creation_date: '26/06/2022 12:18',
    case_key: 'VETCT-107',
    patient: 'Mason Clark',
    status: 'Add History',
    specialty: 'CT',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '27/06/2022 12:18',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '108',
    creation_date: '27/06/2022 09:15',
    case_key: 'VETCT-108',
    patient: 'Jacob White',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'James Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '28/06/2022 09:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '109',
    creation_date: '28/06/2022 11:32',
    case_key: 'VETCT-109',
    patient: 'Mason Harris',
    status: 'Add History',
    specialty: 'XRAY',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '29/06/2022 11:32',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '110',
    creation_date: '29/06/2022 14:45',
    case_key: 'VETCT-110',
    patient: 'Ella Johnson',
    status: 'Reported',
    specialty: 'CT',
    owner: 'James Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '30/06/2022 14:45',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '111',
    creation_date: '30/06/2022 12:18',
    case_key: 'VETCT-111',
    patient: 'Mason Clark',
    status: 'Add History',
    specialty: 'MRI',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '01/07/2022 12:18',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '112',
    creation_date: '01/07/2022 09:15',
    case_key: 'VETCT-112',
    patient: 'Jacob White',
    status: 'Reported',
    specialty: 'XRAY',
    owner: 'James Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '02/07/2022 09:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '113',
    creation_date: '02/07/2022 11:32',
    case_key: 'VETCT-113',
    patient: 'Mason Harris',
    status: 'Add History',
    specialty: 'CT',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '03/07/2022 11:32',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '114',
    creation_date: '03/07/2022 14:45',
    case_key: 'VETCT-114',
    patient: 'Ella Johnson',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'James Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '04/07/2022 14:45',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '115',
    creation_date: '04/07/2022 12:18',
    case_key: 'VETCT-115',
    patient: 'Mason Clark',
    status: 'Add History',
    specialty: 'XRAY',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '05/07/2022 12:18',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '116',
    creation_date: '05/07/2022 09:15',
    case_key: 'VETCT-116',
    patient: 'Jacob White',
    status: 'Reported',
    specialty: 'CT',
    owner: 'James Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '06/07/2022 09:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '117',
    creation_date: '06/07/2022 11:32',
    case_key: 'VETCT-117',
    patient: 'Mason Harris',
    status: 'Add History',
    specialty: 'MRI',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '07/07/2022 11:32',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '118',
    creation_date: '07/07/2022 14:45',
    case_key: 'VETCT-118',
    patient: 'Ella Johnson',
    status: 'Reported',
    specialty: 'XRAY',
    owner: 'James Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '08/07/2022 14:45',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '119',
    creation_date: '08/07/2022 12:18',
    case_key: 'VETCT-119',
    patient: 'Mason Clark',
    status: 'Add History',
    specialty: 'CT',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '09/07/2022 12:18',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '120',
    creation_date: '09/07/2022 09:15',
    case_key: 'VETCT-120',
    patient: 'Jacob White',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'James Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '10/07/2022 09:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '121',
    creation_date: '10/07/2022 11:32',
    case_key: 'VETCT-121',
    patient: 'Mason Harris',
    status: 'Add History',
    specialty: 'XRAY',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '11/07/2022 11:32',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '122',
    creation_date: '11/07/2022 14:45',
    case_key: 'VETCT-122',
    patient: 'Ella Johnson',
    status: 'Reported',
    specialty: 'CT',
    owner: 'James Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '12/07/2022 14:45',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '123',
    creation_date: '12/07/2022 12:18',
    case_key: 'VETCT-123',
    patient: 'Mason Clark',
    status: 'Add History',
    specialty: 'MRI',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '13/07/2022 12:18',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '124',
    creation_date: '13/07/2022 09:15',
    case_key: 'VETCT-124',
    patient: 'Jacob White',
    status: 'Reported',
    specialty: 'XRAY',
    owner: 'James Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '14/07/2022 09:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '125',
    creation_date: '14/07/2022 11:32',
    case_key: 'VETCT-125',
    patient: 'Mason Harris',
    status: 'Add History',
    specialty: 'CT',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '15/07/2022 11:32',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '126',
    creation_date: '15/07/2022 14:45',
    case_key: 'VETCT-126',
    patient: 'Ella Johnson',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'James Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '16/07/2022 14:45',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '127',
    creation_date: '16/07/2022 12:18',
    case_key: 'VETCT-127',
    patient: 'Mason Clark',
    status: 'Add History',
    specialty: 'XRAY',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '17/07/2022 12:18',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '128',
    creation_date: '17/07/2022 09:15',
    case_key: 'VETCT-128',
    patient: 'Jacob White',
    status: 'Reported',
    specialty: 'CT',
    owner: 'James Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '18/07/2022 09:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '129',
    creation_date: '18/07/2022 11:32',
    case_key: 'VETCT-129',
    patient: 'Mason Harris',
    status: 'Add History',
    specialty: 'MRI',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '19/07/2022 11:32',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '130',
    creation_date: '19/07/2022 14:45',
    case_key: 'VETCT-130',
    patient: 'Ella Johnson',
    status: 'Reported',
    specialty: 'XRAY',
    owner: 'James Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '20/07/2022 14:45',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
  {
    id: '131',
    creation_date: '20/07/2022 12:18',
    case_key: 'VETCT-131',
    patient: 'Mason Clark',
    status: 'Add History',
    specialty: 'CT',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '21/07/2022 12:18',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '132',
    creation_date: '21/07/2022 09:15',
    case_key: 'VETCT-132',
    patient: 'Jacob White',
    status: 'Reported',
    specialty: 'MRI',
    owner: 'James Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '22/07/2022 09:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dog-55140_640.jpg',
  },
  {
    id: '133',
    creation_date: '22/07/2022 11:32',
    case_key: 'VETCT-133',
    patient: 'Mason Harris',
    status: 'Add History',
    specialty: 'XRAY',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '23/07/2022 11:32',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '134',
    creation_date: '23/07/2022 14:45',
    case_key: 'VETCT-134',
    patient: 'Ella Johnson',
    status: 'Reported',
    specialty: 'CT',
    owner: 'James Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '24/07/2022 14:45',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '135',
    creation_date: '24/07/2022 12:18',
    case_key: 'VETCT-135',
    patient: 'Mason Clark',
    status: 'Add History',
    specialty: 'MRI',
    owner: 'Brandon Anderson',
    reporting_specialist: 'Joe Blogg',
    species: 'Canine,Golden Retriever',
    body_areas: 'Abdomen,Pelvis',
    turnaround: 'Priority',
    reported_date: '25/07/2022 12:18',
    image_url: 'https://images.dog.ceo/breeds/dachshund/dachshund_4.jpg',
  },
  {
    id: '136',
    creation_date: '25/07/2022 09:15',
    case_key: 'VETCT-136',
    patient: 'Jacob White',
    status: 'Reported',
    specialty: 'XRAY',
    owner: 'James Harris',
    reporting_specialist: 'Annie Lane',
    species: 'Canine,Poodle',
    body_areas: 'Thorax,Spine',
    turnaround: 'Priority',
    reported_date: '26/07/2022 09:15',
    image_url: 'https://images.dog.ceo/breeds/dachshund/Dash_Dachshund_With_Hat.jpg',
  },
];
